-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: May 21, 2022 at 05:31 PM
-- Server version: 10.4.24-MariaDB
-- PHP Version: 8.1.6

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `cafeadb`
--

-- --------------------------------------------------------

--
-- Table structure for table `produse`
--

CREATE TABLE `produse` (
  `idProdus` int(11) NOT NULL,
  `imagine` text NOT NULL,
  `nume` text NOT NULL,
  `pret` int(11) NOT NULL,
  `descriere` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `produse`
--

INSERT INTO `produse` (`idProdus`, `imagine`, `nume`, `pret`, `descriere`) VALUES
(1, '1.webp', 'BRAZIL JOSE BERNARDES', 70, 'Jose Eduardo Bernardes considers that climate during harvest time and the modernization of management and machinery are essential points for obtaining high-quality coffees. Investments and research do not stop there, he is developing new processing methods to meet the increasingly demanding consumer market.\r\n\r\nThis coffee is from Serra Negra farm from which we had past crop’s semi-carbonic processed lot. The same Topazio varietal was selected for this lot which was processed and dried as a classic natural in which coffee beans are left to dry in the cherry then are mechanically peeled. Because of this, the flavor profile has a lower acidity and silky body and more commonly found notes of milk and walnut chocolate.'),
(2, '2.webp', 'BRAZIL SANTA RITA WET FERMENTATION', 80, 'The Cerrado Mineiro region, located in northwest of Minas Gerais State is a world-recognized, high-quality coffee producing origin and became the first Protected Geographical Indication in Brazil in 2005, with full Designation of Origin in 2013. A strong characteristic of this region is its welldefined seasons—a hot, wet summer followed by a pleasantly dry winter. The dry climate during harvest eliminates potential problems with humidity during the drying process.\r\n\r\nInspired by the family experience of growing coffee for more than three decades, Vera Nunes together with her sister Ieda Nunes formed a partnership in 2014 to produce specialty coffees. On the Santa Rita and Barra dos Coqueiros farms, in Patrocínio-MG, a region in the Cerrado region of Minas Gerais famous for its quality coffees, the sisters carried out an agronomic project focused on the production of specialty coffees. The work developed is dedicated to sustainability, with respect for the environment and social and ethical commitment to partners and consumers. The decision to operate in the high quality specialty coffee market and with certification for sustainable agriculture by the Rainforest Alliance from 2017, has allowed Iêda and Vera to participate prominently in specialty coffee competitions.\r\n\r\nThis lot of Yellow Catuai coffee underwent a prolonged fermentation phase called wet fermentation. After pulping the parchment is covered in water which prolongs the fermentation phase. resulting in a fuller body and lively acidity as well as a more refined flavor profile.'),
(3, '3.webp', 'BRAZIL SAO SILVESTRE PULPED NATURAL', 50, 'Elmiro was previously mayor in Patos de Minas, where the farm is located. In 2019, Nascimento was among the top 3 winners of the 28th Ernesto Illy Award for Sustainable Espresso Coffee in Brazil, making him one of the pioneers in promoting the quality of Alto Paranaiba in Cerrado.\r\n\r\nThis Yellow Catuai lot is processed as pulped-natural, a type of processing that was pioneered in Brazil around twenty years ago, where it was originally called Cereja Descascada or “peeled cherry”. This is because the process involves removing the skin of the fruit before letting the coffee dry with almost all of the pulp still on the beans. This method is all about separating ripe fruits and highlighting the sweetness of the coffee – making pulped naturals a consistent aromatic beverage with a superior quality. One of the biggest advantages of this process is that, by removing dried and green beans, you increase the cup quality and decrease the possibility of defects.\r\n\r\nHowever, when compared to the natural process, it’s more expensive and requires a larger amount of water. These coffees normally have the body of a natural coffee and the sweetness and clarity of washed coffees.  '),
(4, '4.webp', 'COLOMBIA GEISHA HERMEL DE JESUS ', 60, 'We are happy to share with you this limited edition anniversary coffee, a very flavourful Colombia Geisha with notes of apricot, green apple, and bergamot with a silky smooth caramel body and lingering buttery aftertaste.\r\n\r\nHermel De Jesus lives on his farm El Danubio high in the Andes in the Department of Caldas in the town of Anserma. Caldas is part of the coffee triangle known locally as the Eje Cafetero.Coffee first came to this region in the mid 19th Century and quickly spread as a profitable crop for farmers. The area has been known for high volume production and commercial coffees but this perception is changing as it now challenges the status quo attributing the best coffees to the southern coffee departments in Colombia.\r\n\r\nEl Danubio a total of 24ha with just 11 ha planted with coffee. The main varieties on the farm are Castillo and Colombia but a few years ago Hermel began to start planting Geisha on the farm to diversity and test the possibilities with this variety. Hermel lives on the farm with his wife, Gloria Cristina Berrio, and coffee is part of the family as he is a third-generation farmer and his father was one of the founding members of the Cooperative de Cafecultores. In the harvest, the coffee is carefully handpicked selecting ripe cherry. This then goes through a second washing and picking before then being pulped and left to ferment for 16 - 24 hours depending on the ambient temperature. After this, the coffee is then washed and floaters removed before then being taken to raised beds to dry for 10 - 14 days weather depending.'),
(5, 'bob.png', 'Lorem Ipsum', 100, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum consectetur gravida augue dictum tristique. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce elementum consectetur arcu id dictum. Etiam eleifend egestas mi in pharetra. Proin pulvinar pellentesque arcu, sit amet dictum erat gravida quis. Suspendisse nulla leo, dignissim pellentesque imperdiet in, blandit sit amet est. Donec quam justo, eleifend ut mi a, pretium varius enim. Morbi gravida felis ut ligula bibendum lobortis. Sed viverra tristique lacus id congue. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras sed ultrices nisl. Pellentesque fringilla lorem et suscipit vehicula. Suspendisse molestie, diam in feugiat pulvinar, diam sem eleifend justo, et euismod ante velit eget sapien. Sed fermentum bibendum sapien, eget placerat leo luctus tempus. Sed iaculis tincidunt est, nec cursus odio elementum id. Pellentesque quis elementum turpis.'),
(6, 'bob.png', 'Lorem Ipsum', 100, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum consectetur gravida augue dictum tristique. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce elementum consectetur arcu id dictum. Etiam eleifend egestas mi in pharetra. Proin pulvinar pellentesque arcu, sit amet dictum erat gravida quis. Suspendisse nulla leo, dignissim pellentesque imperdiet in, blandit sit amet est. Donec quam justo, eleifend ut mi a, pretium varius enim. Morbi gravida felis ut ligula bibendum lobortis. Sed viverra tristique lacus id congue. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras sed ultrices nisl. Pellentesque fringilla lorem et suscipit vehicula. Suspendisse molestie, diam in feugiat pulvinar, diam sem eleifend justo, et euismod ante velit eget sapien. Sed fermentum bibendum sapien, eget placerat leo luctus tempus. Sed iaculis tincidunt est, nec cursus odio elementum id. Pellentesque quis elementum turpis.'),
(7, 'bob.png', 'Lorem Ipsum', 100, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum consectetur gravida augue dictum tristique. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce elementum consectetur arcu id dictum. Etiam eleifend egestas mi in pharetra. Proin pulvinar pellentesque arcu, sit amet dictum erat gravida quis. Suspendisse nulla leo, dignissim pellentesque imperdiet in, blandit sit amet est. Donec quam justo, eleifend ut mi a, pretium varius enim. Morbi gravida felis ut ligula bibendum lobortis. Sed viverra tristique lacus id congue. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras sed ultrices nisl. Pellentesque fringilla lorem et suscipit vehicula. Suspendisse molestie, diam in feugiat pulvinar, diam sem eleifend justo, et euismod ante velit eget sapien. Sed fermentum bibendum sapien, eget placerat leo luctus tempus. Sed iaculis tincidunt est, nec cursus odio elementum id. Pellentesque quis elementum turpis.'),
(8, 'bob.png', 'Lorem Ipsum', 100, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum consectetur gravida augue dictum tristique. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce elementum consectetur arcu id dictum. Etiam eleifend egestas mi in pharetra. Proin pulvinar pellentesque arcu, sit amet dictum erat gravida quis. Suspendisse nulla leo, dignissim pellentesque imperdiet in, blandit sit amet est. Donec quam justo, eleifend ut mi a, pretium varius enim. Morbi gravida felis ut ligula bibendum lobortis. Sed viverra tristique lacus id congue. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras sed ultrices nisl. Pellentesque fringilla lorem et suscipit vehicula. Suspendisse molestie, diam in feugiat pulvinar, diam sem eleifend justo, et euismod ante velit eget sapien. Sed fermentum bibendum sapien, eget placerat leo luctus tempus. Sed iaculis tincidunt est, nec cursus odio elementum id. Pellentesque quis elementum turpis.'),
(9, 'bob.png', 'Lorem Ipsum', 100, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum consectetur gravida augue dictum tristique. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce elementum consectetur arcu id dictum. Etiam eleifend egestas mi in pharetra. Proin pulvinar pellentesque arcu, sit amet dictum erat gravida quis. Suspendisse nulla leo, dignissim pellentesque imperdiet in, blandit sit amet est. Donec quam justo, eleifend ut mi a, pretium varius enim. Morbi gravida felis ut ligula bibendum lobortis. Sed viverra tristique lacus id congue. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras sed ultrices nisl. Pellentesque fringilla lorem et suscipit vehicula. Suspendisse molestie, diam in feugiat pulvinar, diam sem eleifend justo, et euismod ante velit eget sapien. Sed fermentum bibendum sapien, eget placerat leo luctus tempus. Sed iaculis tincidunt est, nec cursus odio elementum id. Pellentesque quis elementum turpis.'),
(10, 'bob.png', 'Lorem Ipsum', 100, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum consectetur gravida augue dictum tristique. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce elementum consectetur arcu id dictum. Etiam eleifend egestas mi in pharetra. Proin pulvinar pellentesque arcu, sit amet dictum erat gravida quis. Suspendisse nulla leo, dignissim pellentesque imperdiet in, blandit sit amet est. Donec quam justo, eleifend ut mi a, pretium varius enim. Morbi gravida felis ut ligula bibendum lobortis. Sed viverra tristique lacus id congue. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras sed ultrices nisl. Pellentesque fringilla lorem et suscipit vehicula. Suspendisse molestie, diam in feugiat pulvinar, diam sem eleifend justo, et euismod ante velit eget sapien. Sed fermentum bibendum sapien, eget placerat leo luctus tempus. Sed iaculis tincidunt est, nec cursus odio elementum id. Pellentesque quis elementum turpis.'),
(11, 'bob.png', 'Lorem Ipsum', 100, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum consectetur gravida augue dictum tristique. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce elementum consectetur arcu id dictum. Etiam eleifend egestas mi in pharetra. Proin pulvinar pellentesque arcu, sit amet dictum erat gravida quis. Suspendisse nulla leo, dignissim pellentesque imperdiet in, blandit sit amet est. Donec quam justo, eleifend ut mi a, pretium varius enim. Morbi gravida felis ut ligula bibendum lobortis. Sed viverra tristique lacus id congue. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras sed ultrices nisl. Pellentesque fringilla lorem et suscipit vehicula. Suspendisse molestie, diam in feugiat pulvinar, diam sem eleifend justo, et euismod ante velit eget sapien. Sed fermentum bibendum sapien, eget placerat leo luctus tempus. Sed iaculis tincidunt est, nec cursus odio elementum id. Pellentesque quis elementum turpis.'),
(12, 'bob.png', 'Lorem Ipsum', 100, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum consectetur gravida augue dictum tristique. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce elementum consectetur arcu id dictum. Etiam eleifend egestas mi in pharetra. Proin pulvinar pellentesque arcu, sit amet dictum erat gravida quis. Suspendisse nulla leo, dignissim pellentesque imperdiet in, blandit sit amet est. Donec quam justo, eleifend ut mi a, pretium varius enim. Morbi gravida felis ut ligula bibendum lobortis. Sed viverra tristique lacus id congue. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras sed ultrices nisl. Pellentesque fringilla lorem et suscipit vehicula. Suspendisse molestie, diam in feugiat pulvinar, diam sem eleifend justo, et euismod ante velit eget sapien. Sed fermentum bibendum sapien, eget placerat leo luctus tempus. Sed iaculis tincidunt est, nec cursus odio elementum id. Pellentesque quis elementum turpis.'),
(13, 'bob.png', 'Lorem Ipsum', 100, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum consectetur gravida augue dictum tristique. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce elementum consectetur arcu id dictum. Etiam eleifend egestas mi in pharetra. Proin pulvinar pellentesque arcu, sit amet dictum erat gravida quis. Suspendisse nulla leo, dignissim pellentesque imperdiet in, blandit sit amet est. Donec quam justo, eleifend ut mi a, pretium varius enim. Morbi gravida felis ut ligula bibendum lobortis. Sed viverra tristique lacus id congue. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras sed ultrices nisl. Pellentesque fringilla lorem et suscipit vehicula. Suspendisse molestie, diam in feugiat pulvinar, diam sem eleifend justo, et euismod ante velit eget sapien. Sed fermentum bibendum sapien, eget placerat leo luctus tempus. Sed iaculis tincidunt est, nec cursus odio elementum id. Pellentesque quis elementum turpis.'),
(14, 'bob.png', 'Lorem Ipsum', 100, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum consectetur gravida augue dictum tristique. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce elementum consectetur arcu id dictum. Etiam eleifend egestas mi in pharetra. Proin pulvinar pellentesque arcu, sit amet dictum erat gravida quis. Suspendisse nulla leo, dignissim pellentesque imperdiet in, blandit sit amet est. Donec quam justo, eleifend ut mi a, pretium varius enim. Morbi gravida felis ut ligula bibendum lobortis. Sed viverra tristique lacus id congue. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras sed ultrices nisl. Pellentesque fringilla lorem et suscipit vehicula. Suspendisse molestie, diam in feugiat pulvinar, diam sem eleifend justo, et euismod ante velit eget sapien. Sed fermentum bibendum sapien, eget placerat leo luctus tempus. Sed iaculis tincidunt est, nec cursus odio elementum id. Pellentesque quis elementum turpis.'),
(15, 'bob.png', 'Lorem Ipsum', 100, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum consectetur gravida augue dictum tristique. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce elementum consectetur arcu id dictum. Etiam eleifend egestas mi in pharetra. Proin pulvinar pellentesque arcu, sit amet dictum erat gravida quis. Suspendisse nulla leo, dignissim pellentesque imperdiet in, blandit sit amet est. Donec quam justo, eleifend ut mi a, pretium varius enim. Morbi gravida felis ut ligula bibendum lobortis. Sed viverra tristique lacus id congue. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras sed ultrices nisl. Pellentesque fringilla lorem et suscipit vehicula. Suspendisse molestie, diam in feugiat pulvinar, diam sem eleifend justo, et euismod ante velit eget sapien. Sed fermentum bibendum sapien, eget placerat leo luctus tempus. Sed iaculis tincidunt est, nec cursus odio elementum id. Pellentesque quis elementum turpis.'),
(16, 'bob.png', 'Lorem Ipsum', 100, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum consectetur gravida augue dictum tristique. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce elementum consectetur arcu id dictum. Etiam eleifend egestas mi in pharetra. Proin pulvinar pellentesque arcu, sit amet dictum erat gravida quis. Suspendisse nulla leo, dignissim pellentesque imperdiet in, blandit sit amet est. Donec quam justo, eleifend ut mi a, pretium varius enim. Morbi gravida felis ut ligula bibendum lobortis. Sed viverra tristique lacus id congue. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras sed ultrices nisl. Pellentesque fringilla lorem et suscipit vehicula. Suspendisse molestie, diam in feugiat pulvinar, diam sem eleifend justo, et euismod ante velit eget sapien. Sed fermentum bibendum sapien, eget placerat leo luctus tempus. Sed iaculis tincidunt est, nec cursus odio elementum id. Pellentesque quis elementum turpis.'),
(17, 'bob.png', 'Lorem Ipsum', 100, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum consectetur gravida augue dictum tristique. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce elementum consectetur arcu id dictum. Etiam eleifend egestas mi in pharetra. Proin pulvinar pellentesque arcu, sit amet dictum erat gravida quis. Suspendisse nulla leo, dignissim pellentesque imperdiet in, blandit sit amet est. Donec quam justo, eleifend ut mi a, pretium varius enim. Morbi gravida felis ut ligula bibendum lobortis. Sed viverra tristique lacus id congue. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras sed ultrices nisl. Pellentesque fringilla lorem et suscipit vehicula. Suspendisse molestie, diam in feugiat pulvinar, diam sem eleifend justo, et euismod ante velit eget sapien. Sed fermentum bibendum sapien, eget placerat leo luctus tempus. Sed iaculis tincidunt est, nec cursus odio elementum id. Pellentesque quis elementum turpis.'),
(18, 'bob.png', 'Lorem Ipsum', 100, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum consectetur gravida augue dictum tristique. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce elementum consectetur arcu id dictum. Etiam eleifend egestas mi in pharetra. Proin pulvinar pellentesque arcu, sit amet dictum erat gravida quis. Suspendisse nulla leo, dignissim pellentesque imperdiet in, blandit sit amet est. Donec quam justo, eleifend ut mi a, pretium varius enim. Morbi gravida felis ut ligula bibendum lobortis. Sed viverra tristique lacus id congue. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras sed ultrices nisl. Pellentesque fringilla lorem et suscipit vehicula. Suspendisse molestie, diam in feugiat pulvinar, diam sem eleifend justo, et euismod ante velit eget sapien. Sed fermentum bibendum sapien, eget placerat leo luctus tempus. Sed iaculis tincidunt est, nec cursus odio elementum id. Pellentesque quis elementum turpis.'),
(19, 'bob.png', 'Lorem Ipsum', 100, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum consectetur gravida augue dictum tristique. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce elementum consectetur arcu id dictum. Etiam eleifend egestas mi in pharetra. Proin pulvinar pellentesque arcu, sit amet dictum erat gravida quis. Suspendisse nulla leo, dignissim pellentesque imperdiet in, blandit sit amet est. Donec quam justo, eleifend ut mi a, pretium varius enim. Morbi gravida felis ut ligula bibendum lobortis. Sed viverra tristique lacus id congue. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras sed ultrices nisl. Pellentesque fringilla lorem et suscipit vehicula. Suspendisse molestie, diam in feugiat pulvinar, diam sem eleifend justo, et euismod ante velit eget sapien. Sed fermentum bibendum sapien, eget placerat leo luctus tempus. Sed iaculis tincidunt est, nec cursus odio elementum id. Pellentesque quis elementum turpis.'),
(20, 'bob.png', 'Lorem Ipsum', 100, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum consectetur gravida augue dictum tristique. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce elementum consectetur arcu id dictum. Etiam eleifend egestas mi in pharetra. Proin pulvinar pellentesque arcu, sit amet dictum erat gravida quis. Suspendisse nulla leo, dignissim pellentesque imperdiet in, blandit sit amet est. Donec quam justo, eleifend ut mi a, pretium varius enim. Morbi gravida felis ut ligula bibendum lobortis. Sed viverra tristique lacus id congue. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras sed ultrices nisl. Pellentesque fringilla lorem et suscipit vehicula. Suspendisse molestie, diam in feugiat pulvinar, diam sem eleifend justo, et euismod ante velit eget sapien. Sed fermentum bibendum sapien, eget placerat leo luctus tempus. Sed iaculis tincidunt est, nec cursus odio elementum id. Pellentesque quis elementum turpis.'),
(21, 'bob.png', 'Lorem Ipsum', 100, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum consectetur gravida augue dictum tristique. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce elementum consectetur arcu id dictum. Etiam eleifend egestas mi in pharetra. Proin pulvinar pellentesque arcu, sit amet dictum erat gravida quis. Suspendisse nulla leo, dignissim pellentesque imperdiet in, blandit sit amet est. Donec quam justo, eleifend ut mi a, pretium varius enim. Morbi gravida felis ut ligula bibendum lobortis. Sed viverra tristique lacus id congue. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras sed ultrices nisl. Pellentesque fringilla lorem et suscipit vehicula. Suspendisse molestie, diam in feugiat pulvinar, diam sem eleifend justo, et euismod ante velit eget sapien. Sed fermentum bibendum sapien, eget placerat leo luctus tempus. Sed iaculis tincidunt est, nec cursus odio elementum id. Pellentesque quis elementum turpis.');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `produse`
--
ALTER TABLE `produse`
  ADD PRIMARY KEY (`idProdus`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `produse`
--
ALTER TABLE `produse`
  MODIFY `idProdus` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=22;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
